# Site settings
title: io.zwets.it
email: io@zwets.it
description: "Marco van Zwetselaar's IT domain"
#baseurl: ""
url: "https://io.zwets.it"
github_username:  zwets
mastodon_username:  zwets
TZ: Africa/Dar_es_Salaam
exclude: ["Gemfile", "Gemfile.lock", "vendor", "README.md", "LICENSE", "CNAME", "new-post.sh"]
#include: [".htaccess"] # default, because dotfiles otherwise ignored in generation
#keep_files: [".git",".svn"] # files in destination that should remain (but Github might clear all?)
#show_drafts: null
#limit_posts: 0
#future:      false
#unpublished: false

# Collections
collections:
  notes:
    output: true

defaults:
  - scope:
      path: "" # any path
      type: notes
    values:
      layout: page
      permalink: /:name
      author: "zwets"

# Conversion
#markdown:    kramdown # default since GH on Jekyll 3
#highlighter: rouge # default since GH went to Jekyll 3
#excerpt_separator: "\n\n"
#incremental: false

# Build settings
#markdown: kramdown
permalink: pretty
timezone: Africa/Dar_es_Salaam
#jekyll.environment: production # default is development?
gems:
  - jekyll-sitemap

# Kramdown options
kramdown:
  input: GFM   # Github Flavoured Markdown
  toc_levels: 1..3
  hard_wrap: false      # Override Github default
#  auto_ids:       true
#  footnote_nr:    1
#  entity_output:  as_char
#  toc_levels:     1..6
#  smart_quotes:   lsquo,rsquo,ldquo,rdquo

# (Non-overrideable) Github defaults
#safe: true
#lsi: false
#source: your top-level directory

# (Overrideable) Github defaults
#github: [Repository metadata] 
# See: https://help.github.com/articles/repository-metadata-on-github-pages/
# site.github.{url,owner_url,build_revision,api_url,owner_gravatar_url, ...}

# Page defaults (see http://jekyllrb.com/docs/configuration/)
#defaults:
#  -
#    scope:
#      path: ""  # any path
#      type: posts # but only of type posts (other options are: pages, drafts)
#    values:
#      layout: post
#      author: "zwets"
#  -

