# Site settings
title: io.zwets.it
email: io@zwets.it
description: "Marco van Zwetselaar's IT domain"
#baseurl: ""
url: "http://io.zwets.it"
github_username:  zwets
TZ: Africa/Dar_es_Salaam
#exclude: # dirs and file to exclude from site
#include: [".htaccess"] # default, because dotfiles otherwise ignored in generation
#keep_files: [".git",".svn"] # files in destination that should remain (but Github might clear all?)
#show_drafts: null
#limit_posts: 0
#future:      false
#unpublished: false
# Conversion
#markdown:    kramdown
#highlighter: rouge
highlighter: pygments
#lsi:         false
#excerpt_separator: "\n\n"
#incremental: false

# Build settings
markdown: kramdown
permalink: pretty
timezone: Africa/Dar_es_Salaam
#jekyll.environment: production # default is development?

kramdown:
  input: GFM   # Github Flavoured Markdown

# (Non-overrideable) Github defaults
#safe: true
#lsi: false
#source: your top-level directory
# (Overrideable) Github defaults
#highlighter: pygments
#github: [Repository metadata] 
# See: https://help.github.com/articles/repository-metadata-on-github-pages/
# site.github.{url,owner_url,build_revision,api_url,owner_gravatar_url, ...}

# Page defaults (see http://jekyllrb.com/docs/configuration/)
#defaults:
#  -
#    scope:
#      path: ""  # any path
#      type: posts # but only of type posts (other options are: pages, drafts)
#    values:
#      layout: post
#      author: "zwets"
#  -
#    scope:
#      path: "" # any path
#      type: pages
#    values:
#      layout: page
#      author: "zwets"

